src/Models/DomainModels/Cart.cs
using Microsoft.AspNetCore.Http;
using Book_Store.Models.DataLayer;
using Book_Store.Models.DataLayer.Repositories;
using Book_Store.Models.DTOs;
using Book_Store.Models.ExtensionMethods;
using System.Collections.Generic;
using System.Linq;

namespace Book_Store.Models.DomainModels
{
  // Cart class stores CartItem objects in session and persistent cookies.
  public class Cart
  {
    private const string CartKey = "mycart";
    private const string CountKey = "mycount";

    private List<CartItem> items { get; set; }
    private List<CartItemDTO> storedItems { get; set; }

    private ISession session { get; set; }
    private IRequestCookieCollection requestCookies { get; set; }
    private IResponseCookies responseCookies { get; set; }

    public Cart(HttpContext ctx)
    {
      session = ctx.Session;
      requestCookies = ctx.Request.Cookies;
      responseCookies = ctx.Response.Cookies;
    }

    public void Load(Repository<Book> data)
    {
      items = session.GetObject<List<CartItem>>(CartKey);
      if (items == null)
      {
        items = new List<CartItem>();
        storedItems = requestCookies.GetObject<List<CartItemDTO>>(CartKey);
      }

      if(storedItems?.Count > items?.Count)
      {
        foreach(CartItemDTO storedItem in storedItems)
        {
          var book = data.Get(new QueryOptions<Book>
          {
            Includes = "BookAuthors.Author, Genre",
            Where = b => b.BookId == storedItem.BookId
          });

          if (book != null)
          {
            var dto = new BookDTO();
            dto.Load(book);

            CartItem item = new CartItem
            {
              Book = dto,
              Quantity = storedItem.Quantity
            };

            items.Add(item);
          }
        }
        Save();
      }
    }

    public double Subtotal => items.Sum(i => i.Subtotal);
    public int? Count => session.GetInt32(CountKey) ?? requestCookies.GetInt32(CountKey);
    public IEnumerable<CartItem> List => items;

    public CartItem GetById(int id) => items.FirstOrDefault(ci => ci.Book.BookId == id);

    // if the user clicks "Add to Cart" and the item
    // is already in the cart, it's updated rather than duplicated.
    public void Add(CartItem item)
    {
      var itemInCart = GetById(item.Book.BookId);
      //if new then add it
      if (itemInCart == null)
        items.Add(item);
      else // otherwise, increase quantity amount by 1
        itemInCart.Quantity += 1;
    }

    // when editing, replace quantity value with new one. Used when user edits a cart item
    // and changes its quantity
    public void Edit(CartItem item)
    {
      var itemInCart = GetById(item.Book.BookId);
      if (itemInCart != null)
        itemInCart.Quantity = item.Quantity;
    }

    public void Remove(CartItem item) => items.Remove(item);
    public void Clear() => items.Clear();

    // stores updated cart items and new count in session and persistent cookie (stores smaller DTO in cookie). 
    // If count is zero, removes cart and count from session and cookie (this is so cart badge in navbar disappears 
    // when cart is emptied, rather than showing with a value of zero). 
    public void Save()
    {
      if (items.Count == 0)
      {
        session.Remove(CartKey);
        session.Remove(CountKey);
        responseCookies.Delete(CartKey);
        responseCookies.Delete(CountKey);
      }
      else
      {
        session.SetObject<List<CartItem>>(CartKey, items);
        session.SetInt32(CountKey, items.Count);
        responseCookies.SetObject<List<CartItemDTO>>(CartKey, items.ToDTO());
        responseCookies.SetInt32(CountKey, items.Count);
      }
    }
  }
}

src/Models/ViewModels/CartViewModel.cs
using Book_Store.Models.DomainModels;
using Book_Store.Models.Grid;
using System.Collections.Generic;


namespace Book_Store.Models.ViewModels
{
  public class CartViewModel
  {
    public IEnumerable<CartItem> List { get; set; }
    public double Subtotal { get; set; }
    public RouteDictionary BookGridRoute { get; set; }

  }
}

src/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Book_Store.Models.DataLayer;
using Book_Store.Models.DataLayer.Repositories;
using Book_Store.Models.DomainModels;
using Book_Store.Models.DTOs;
using Book_Store.Models.ExtensionMethods;
using Book_Store.Models.Grid;
using Book_Store.Models.ViewModels;

namespace Book_Store.Controllers
{
  public class AuthorController : Controller
  {
    private Repository<Author> data { get; set; }

    public AuthorController(BookstoreContext ctx) => data = new Repository<Author>(ctx);

    public IActionResult Index() => RedirectToAction("List");

    // dto has properties for the paging and sorting route segments defined in the Startup.cs file
    public ViewResult List (GridDTO vals)
    {
      // get grid builder, which loads route segment values and stores them in session
      string defaultSort = nameof(Author.LastName);
      var builder = new GridBuilder(HttpContext.Session, vals, defaultSort);
      builder.SaveRouteSegment();

      // create options for querying authors. OrderBy depends on value in SortField route 
      var options = new QueryOptions<Author>
      {
        Includes = "BookAuthors.Book",
        PageNumber = builder.CurrentRoute.PageNumber,
        PageSize = builder.CurrentRoute.PageSize,
        OrderByDirection = builder.CurrentRoute.SortDirection
      };

      if (builder.CurrentRoute.SortField.EqualsNoCase(defaultSort))
        options.OrderBy = a => a.LastName;
      else
        options.OrderBy = a => a.FirstName;

      // create view model and add page of author data, the current route,
      // and the total number of pages

      var vm = new AuthorListViewModel
      {
        Authors = data.List(options),
        CurrentRoute = builder.CurrentRoute,
        TotalPages = builder.GetTotalPages(data.Count)
      };

      return View(vm);
    }

    public ViewResult Details(int id)
    {
      var author = data.Get(new QueryOptions<Author>
      {
        Includes = "BookAuthors.Book",
        Where = a => a.AuthorId == id
      });

      return View(author);
    }
  }
}

src/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Book_Store.Models.DataLayer;
using Book_Store.Models.DataLayer.Repositories;
using Book_Store.Models.DomainModels;
using Book_Store.Models.DTOs;
using Book_Store.Models.Grid;
using Book_Store.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Localization;

namespace Book_Store.Controllers
{

  [Authorize]
  public class CartController : Controller
  {
    private readonly IHtmlLocalizer<CartController> _localizer;

    private Repository<Book> data { get; set; }

    public CartController(BookstoreContext ctx, IHtmlLocalizer<CartController> localizer)
    {
        data = new Repository<Book>(ctx);
        _localizer = localizer;
    }

    private Cart GetCart()
    {
      var cart = new Cart(HttpContext);
      cart.Load(data);
      return cart;
    }

    public IActionResult Index()
    {
      // create a new Cart object and get items from session or restore from cookie and db
      Cart cart = GetCart();

      // create a new builder object to work with route data in session
      var builder = new BooksGridBuilder(HttpContext.Session);

      // create a new view model object with cart and route information and pass it to the view
      var vm = new CartViewModel
      {
        List = cart.List,
        Subtotal = cart.Subtotal,
        BookGridRoute = builder.CurrentRoute
      };

      return View(vm);
    }

    [HttpPost]
    public RedirectToActionResult Add(int id)
    {
      // get the book the user chose from the database
      var book = data.Get(new QueryOptions<Book>
      {
        Includes = "BookAuthors.Author, Genre",
        Where = b => b.BookId == id
      });

      if (book == null)
      {
        TempData["message"] = _localizer["Add Error"];
      }
      else
      {
        // create and load a new Book DTO, then add it to a new CartItem object
        // with a default quantity of one.
        var dto = new BookDTO();
        dto.Load(book);
        CartItem item = new CartItem
        {
          Book = dto,
          Quantity = 1 //default quantity
        };

        // add new item to cart and save to session state
        Cart cart = GetCart();
        cart.Add(item);
        cart.Save();

        TempData["message"] = $"{book.Title} {_localizer["Added to Cart"].Value}";
      }

      // create a new builder object to work with route data in session, then 
      // redirect to Book/List action method, passing a dictionary of route segment 
      // values to build URL 
      var builder = new BooksGridBuilder(HttpContext.Session);
      return RedirectToAction("List", "Book", builder.CurrentRoute);
    }

    [HttpPost]
    public RedirectToActionResult Remove(int id)
    {
      Cart cart = GetCart();
      CartItem item = cart.GetById(id);
      cart.Remove(item);
      cart.Save();

      TempData["message"] = $"{item.Book.Title} {_localizer["Removed from Cart"].Value}";
      return RedirectToAction("Index");
    }

    [HttpPost]
    public RedirectToActionResult Clear()
    {
      Cart cart = GetCart();
      cart.Clear();
      cart.Save();

      TempData["message"] =  _localizer["Cleared Cart"].Value;
      return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
      // get selected cart item from session and pass it to the view
      Cart cart = GetCart();
      CartItem item = cart.GetById(id);

      if (item == null)
      {
        TempData["message"] = _localizer["Located Error"].Value;
        return RedirectToAction("Index");
      }
      else
      {
        return View(item);
      }
    }

    [HttpPost]
    public RedirectToActionResult Edit(CartItem item)
    {
      Cart cart = GetCart();
      cart.Edit(item);
      cart.Save();

      TempData["message"] = $"{item.Book.Title} {_localizer["Updated Cart"].Value}";
      return RedirectToAction("Index");
    }

    public ViewResult Checkout() => View();
  }
}

src/Views/Cart/Checkout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{ 
  ViewData["Title"] = "Checkout";
}

<h1>@localizer["Checkout"]</h1>
<ul class="list-group">
  <li class="list-group-item">
    <h4>@localizer["Message1"]</h4>
  </li>
  <li class="list-group-item">
    @localizer["Message2"]
  </li>
</ul>

src/Views/Cart/Edit.cshtml
@model Book_Store.Models.DomainModels.CartItem
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{ 
  ViewData["Title"] = " | Edit Cart";
}

<h1>@localizer["Edit Cart Item"]</h1>
<form asp-controller="Cart" asp-action="Edit" method="post">
  <ul class="list-group mb-2">
    <li class="list-group-item">@Model.Book.Title</li>
    <li class="list-group-item">
      <div class="col-1">
        <label>@localizer["Price"]:</label>
      </div>
      <div class="col-1">
        @Model.Book.Price.ToString("c")
      </div>
    </li>
    <li class="list-group-item">
      <div class="form-row">
        <div class="col-1">
          <label asp-for="Quantity">@localizer["Quantity"]:</label>
        </div>
        <div class="col-1">
          <select asp-for="Quantity" class="form-control">
            @for(int i = 1; i <= 10; i++)
            {
              <option>@i</option>
            }
          </select>
        </div>
      </div>
    </li>
  </ul>
  <input type="hidden" asp-for="Book.BookId" />
  <input type="hidden" asp-for="Book.Title" />

  <button type="submit" class="btn btn-primary">@localizer["Save"]</button>
  <a asp-controller="Cart" asp-action="Index" class="btn btn-primary">@localizer["Cancel"]</a>
</form>

src/Views/Cart/Index.cshtml
@model Book_Store.Models.ViewModels.CartViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

@{ 
  ViewData["Title"] = " | Cart";
}

<h1>@localizer["Your Cart"]</h1>
<form asp-controller="Cart" asp-action="Clear" method="post">
  <ul>
    <li class="list-group-item">
      <div class="row">
        <div class="col">
          @localizer["Total"]: @Model.Subtotal.ToString("c")
        </div>
        <div class="col">
          <div class="float-right">
            <a asp-controller="Cart" asp-action="Checkout" class="btn btn-primary">@localizer["Checkout"]</a>
            <button type="submit" class="btn btn-primary">@localizer["Clear"]</button>
            <a asp-controller="Book" asp-action="List" asp-all-route-data="@Model.BookGridRoute">
              @localizer["Back to Shopping"]
            </a>
          </div>
        </div>
      </div>
    </li>
  </ul>
</form>
<form asp-controller="Cart" asp-action="Remove" method="post">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>@localizer["Title"]</th>
        <th>@localizer["Authors"]</th>
        <th>@localizer["Price"]</th>
        <th>@localizer["Quantity"]</th>
        <th>@localizer["Subtotal"]</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach(Book_Store.Models.DomainModels.CartItem item in Model.List)
      {
        <tr>
          <td>
            <a asp-controller="Book" asp-action="Details" asp-route-id="@item.Book.BookId">
              @item.Book.Title
            </a>
          </td>
          <td>
            @foreach(var keyValuePair in item.Book.Authors)
            {
              <p>
                <a asp-controller="Author" asp-action="Details" asp-route-id="keyValuePair.Key">
                  @keyValuePair.Value
                </a>
              </p>
            }
          </td>
          <td>@item.Book.Price.ToString("c")</td>
          <td>@item.Quantity</td>
          <td>@item.Subtotal.ToString("c")</td>
          <td>
            <div class="float-right">
              <a asp-controller="Cart" asp-action="Edit" asp-route-id="@item.Book.BookId" class="btn btn-primary">@localizer["Edit"]</a>
              <button type="submit" name="id" value="@item.Book.BookId" class="btn btn-primary">@localizer["Remove"]</button>
            </div>
          </td>
        </tr>
      }
    </tbody>
  </table>
</form>